### ISSUE TITLE
Make slug field non-editable

### ISSUE THREAD

**Issue by langdonholmes** [learlab/strapi#49]
To prevent issues where iTELL AI and NextJS have different ideas of what a page slug is, we should lock this field.

We may decide to make slugs editable again in the future once we sort out a more reliable syncing mechanism.

**Comment by theannachen** [comment]
This was changed through the admin panel directly and should be reflected for everyone now. Feel free to open this back up if that solution isn't adequate.

**Comment by langdonholmes** [comment]
Great! Thanks Anna.
